// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTerminalsServer.Dal;

#nullable disable

namespace WebTerminalsServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230323193449_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTerminalsServer.Logic.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NextLegId")
                        .HasColumnType("int");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextLegId");

                    b.HasIndex("flightId");

                    b.ToTable("legs");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeparture")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.Property<int>("legId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("flightId");

                    b.HasIndex("legId");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("WebTerminalsServer.Logic.Leg", b =>
                {
                    b.HasOne("WebTerminalsServer.Logic.Leg", "NextLeg")
                        .WithMany()
                        .HasForeignKey("NextLegId");

                    b.HasOne("WebTerminalsServer.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextLeg");

                    b.Navigation("flight");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.Logger", b =>
                {
                    b.HasOne("WebTerminalsServer.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebTerminalsServer.Logic.Leg", "leg")
                        .WithMany()
                        .HasForeignKey("legId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");

                    b.Navigation("leg");
                });
#pragma warning restore 612, 618
        }
    }
}
