// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTerminalsServer.Dal;

#nullable disable

namespace WebTerminalsServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTerminalsServer.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeparture")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.LegModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("NextLeg")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Legs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NextLeg = 2,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            NextLeg = 4,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            NextLeg = 8,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            NextLeg = 16,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            NextLeg = 32,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            NextLeg = 128,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            NextLeg = 128,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            NextLeg = 8,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            NextLeg = 0,
                            Number = 9
                        });
                });

            modelBuilder.Entity("WebTerminalsServer.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEntering")
                        .HasColumnType("bit");

                    b.Property<int?>("LegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("LegId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.LegModel", b =>
                {
                    b.HasOne("WebTerminalsServer.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("WebTerminalsServer.Models.Logger", b =>
                {
                    b.HasOne("WebTerminalsServer.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.HasOne("WebTerminalsServer.Models.LegModel", "Leg")
                        .WithMany()
                        .HasForeignKey("LegId");

                    b.Navigation("Flight");

                    b.Navigation("Leg");
                });
#pragma warning restore 612, 618
        }
    }
}
